name: Publish to Azure App Service

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: The name of the artifact to publish.
        required: true
      resource-group:
        type: string
        description: The name of the resource group to publish to.
        required: true
      app-name:
        type: string
        description: The App Service name.
        required: true
      publish-dir:
        type: string
        description: The directory containing the artifacts to publish (defaults to the current directory).
        required: false
        default: .
      slot-name:
        type: string
        description: The deployment slot to use.
        required: false
      migrations-script:
        type: string
        description: The path to the .sql file to apply migrations to the database.
        required: true
    secrets:
      azure-credentials:
        required: true
      db-server-name:
        description: The name of the database server.
        required: true
      db-connection-string:
        description: The connection string to the database.
        required: true

jobs:
  publish:
    name: Deploy microservice to Azure
    runs-on: windows-2019
    concurrency: deploy-${{ inputs.app-name }}-${{ inputs.slot-name || 'production' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}
      - name: Stop the web app
        run: |
          if [[ -n '${{ inputs.slot-name }}' ]]; then
            SLOT='--slot ${{ inputs.slot-name }}'
          fi
          az webapp stop --resource-group '${{ inputs.resource-group }}' --name '${{ inputs.app-name }}' $SLOT
      - name: Apply database migrations
        uses: azure/sql-action@v1
        with:
          server-name: ${{ secrets.db-server-name }}
          connection-string: ${{ secrets.db-connection-string }}
          sql-file: ${{ inputs.migrations-script }}
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          package: ${{ inputs.publish-dir }}
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name || 'production' }}
      - name: Restart the web app
        run: |
          if [[ -n '${{ inputs.slot-name }}' ]]; then
            SLOT='--slot ${{ inputs.slot-name }}'
          fi
          az webapp start --resource-group '${{ inputs.resource-group }}' --name '${{ inputs.app-name }}' $SLOT
